/*
 * This source file was generated by the Gradle 'init' task
 */
package usace.hec;
import usace.cc.plugin.api.*;
import usace.cc.plugin.api.IOManager.InvalidDataStoreException;

public class BootstrapEventGenerator {
    public static void main(String[] args) {
        if(args[0]!="useLocal"){
            PluginManager pm;
            try {
                pm = PluginManager.getInstance();
            } catch (InvalidDataStoreException e) {
                e.printStackTrace();
                System.out.println("could not find one of the datastores in payload to register.");
                System.exit(-1);
                return;
            }            
        }

        return;
    }
}
