/*
 * This source file was generated by the Gradle 'init' task
 */
package usace.hec.model.io;

import static org.junit.Assert.assertThrows;
import static org.junit.Assert.assertTrue;

import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Optional;

import org.junit.Test;
import org.junit.Rule;
import uk.org.webcompere.systemstubs.rules.EnvironmentVariablesRule;
import usace.cc.plugin.api.DataStore;
import usace.cc.plugin.api.DataStoreTypeRegistry;
import usace.cc.plugin.api.IOManager.InvalidDataStoreException;
import usace.cc.plugin.api.PluginManager;
import usace.cc.plugin.api.StoreType;
import usace.hec.io.CsvEventStore;
import usace.hec.model.timeseries.TimeSeries;
import usace.hec.model.timeseries.TimeSeriesRecord;

public class CsvEventStoreTest {
    @Rule
    public EnvironmentVariablesRule environmentVariables = new EnvironmentVariablesRule();

    @Test
    public void simpleCSVTesting() {
        environmentVariables.set("CC_STORE_TYPE", "FS");
        environmentVariables.set("CC_EVENT_IDENTIFIER", "1");
        environmentVariables.set("WAT_REALIZATION", "2");
        environmentVariables.set("WAT_LIFECYCLE", "3");
        environmentVariables.set("WAT_ALTERNATIVE", "wop");
        environmentVariables.set("WAT_ANALYSIS_PERIOD", "base");
        environmentVariables.set("WAT_SIMULATION", "wop-base");
        environmentVariables.set("CC_STORE_TYPE", "FS");
        environmentVariables.set("FSB_ROOT_PATH", "/workspaces/bootstrap-event-generator-plugin/lib/src/test/resources/wat/runs");
        //need to register the connection datastore for the csv reader
        DataStoreTypeRegistry.registry.put(StoreType.WS, CsvEventStore.class);
        PluginManager pm;
        try {
            pm = PluginManager.getInstance();
        } catch (InvalidDataStoreException e) {
            e.printStackTrace();
            System.out.println("could not find one of the datastores in payload to register.");
            System.exit(-1);
            return;
        } catch (Exception e2){
            e2.printStackTrace();
            System.out.println("probably an issue connecting to the cc_store.");
            System.exit(-1);
            return;
        }
        Optional<DataStore> ds = pm.getPayload().getStore("EVENT_STORE");
        TimeSeriesRecord[] records = new TimeSeriesRecord[3];
        DateTimeFormatter customFormatter = DateTimeFormatter.ofPattern("ddMMMyyyy");
        records[0] = new TimeSeriesRecord(ZonedDateTime.now().format(customFormatter), 1.0d);
        records[1] = new TimeSeriesRecord(ZonedDateTime.now().format(customFormatter), 2.0d);
        records[2] = new TimeSeriesRecord(ZonedDateTime.now().format(customFormatter), 3.0d);
        TimeSeries ts = new TimeSeries("event_1/ts.csv", records);
        ts.Write(ds.get());
        TimeSeries tsread = ts.Read(ds.get(), "event_1/ts.csv",1l,3l);
        assertTrue(records[2].Value==tsread.timeSeries[2].Value);
    }

}