/*
 * This source file was generated by the Gradle 'init' task
 */
package usace.hec;

import static org.junit.Assert.assertThrows;

import org.junit.Test;

import usace.hec.BootstrapEventGenerator;

public class BootstrapEventGeneratorTest {
    @Test public void mainMethodDoesNotThrowException() {
        String[] args = new String[]{"useLocal"};
        BootstrapEventGenerator.main(args);
    }
    @Test public void mainMethodThrowsException() {
        String[] args = new String[]{"abc"};
        assertThrows(java.lang.IllegalArgumentException.class, () ->{BootstrapEventGenerator.main(args);});
    }
}
