/*
 * This source file was generated by the Gradle 'init' task
 */
package usace.hec;

import static org.junit.Assert.assertThrows;

import org.junit.Test;
import org.junit.Rule;
import uk.org.webcompere.systemstubs.rules.EnvironmentVariablesRule;

public class BootstrapEventGeneratorTest {
    @Rule
    public EnvironmentVariablesRule environmentVariables = new EnvironmentVariablesRule();

    @Test
    public void mainMethodDoesNotThrowException() {
        environmentVariables.set("CC_STORE_TYPE", "FS");
        environmentVariables.set("CC_EVENT_IDENTIFIER", "1");
        environmentVariables.set("WAT_REALIZATION", "2");
        environmentVariables.set("WAT_LIFECYCLE", "3");
        environmentVariables.set("WAT_ALTERNATIVE", "wop");
        environmentVariables.set("WAT_ANALYSIS_PERIOD", "base");
        environmentVariables.set("WAT_SIMULATION", "wop-base");
        environmentVariables.set("CC_STORE_TYPE", "FS");
        environmentVariables.set("FSB_ROOT_PATH", "/workspaces/bootstrap-event-generator-plugin/lib/src/test/resources/");
        BootstrapEventGenerator.main(null);
    }
    @Test public void mainMethodThrowsException() {
        environmentVariables.set("CC_STORE_TYPE", "S3");
        environmentVariables.set("CC_AWS_DEFAULT_REGION", "us-gov-west-1");
        assertThrows(java.lang.NullPointerException.class, () ->{BootstrapEventGenerator.main(null);});
    }
}
