/*
 * This source file was generated by the Gradle 'init' task
 */
package usace.hec;

import org.junit.Test;

import usace.hec.BootstrapEventGenerator;

public class BootstrapEventGeneratorTest {
    @Test public void someLibraryMethodReturnsTrue() {
        String[] args = new String[]{"useLocal"};
        usace.hec.BootstrapEventGenerator.main(args);;
    }
}
